language: node_js
node_js: "node"
addons:
  sauce_connect: true
  hosts:
    - localhost.local
script:
- yarn run build
- yarn run tslint
- yarn run e2e-update
- yarn run e2e-travis
- if [[ -d .test-results ]]; then tar -cz .test-results > test-results.tgz; node e2e/log-results.js; fi
